spring.application.name=Spring-AI-Project

server.port=8080

# ==========================================
# OLLAMA CONFIGURATION
# ==========================================

# Ollama URL
spring.ai.ollama.base-url=http://localhost:11434

# Chat Model
spring.ai.ollama.chat.model=tinyllama

# Embedding Model
spring.ai.ollama.embedding.options.model=mxbai-embed-large

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.ai=DEBUG
