spring.application.name=Spring-AI-Project

server.port=8080

# ==========================================
# OLLAMA CONFIGURATION
# ==========================================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.ai=DEBUG
