spring.application.name=Spring-AI-Project
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OLLAMA
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=tinyllama
spring.ai.ollama.embedding.model=nomic-embed-text

# PG VECTOR STORE
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.index-type=hnsw

# Disable Docker Compose auto-management (container already running)
spring.docker.compose.enabled=false

spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always

spring.main.allow-bean-definition-overriding=true